[package]
name = "shannon"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii = "1.1.0"
byteorder = "1.5.0"
const-crc32 = "1.3.0"
env_logger = "0.11.5"
log = "0.4.22"
nom = "7.1.3"
rand = "0.8.5"
thiserror = "1.0.65"
